# config.yml

analysis:
  ai_model: "gpt-4o-mini"
  file_extensions: [".py", ".cpp"]

ai_settings:
  ai_model: gpt-4o-mini
  temperature: 0.7
  max_tokens: 1000
  code_style: 
    .py: PEP-8
    .cpp : Google c++ Style